spring:
  application:
    name: PVI_Francisco_Lopez
  datasource:
    url: jdbc:mariadb://localhost:3306/pvi
    username: root
    password: Francisco31.
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: franciscom.290794@gmail.com
    password: fodvthgfziajvles
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

app:
  upload:
    # dir: C:\\springWeb\\
    dir: /Users/franciscolopez/imagesProyectos/springWeb/
  api:
    url: http://localhost:8080/api

jwt:
  secret: 5f39c83d2d0482e07b5306f3f5a0fd8e1b4e9844987121ba4b99f3f4805fd4f85cc0f24ece8556dd10456a45d20cd2d61e7c36a77583674be979b071b869f34f
  expirationDateInMs: 3600
  refreshExpirationDateInMs: 900