spring:
  application:
    name: PVI_Francisco_Lopez
  datasource:
    url: jdbc:mariadb://localhost:3306/pvi
    username: root
    password: Francisco31.
    driver-class-name: org.mariadb.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  jpa:
    show-sql: false
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 8080
app:
  upload:
    # dir: C:\\springWeb\\
    dir: /Users/franciscolopez/imagesProyectos/springWeb/
  api:
    url: http://localhost:8080/api
